# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-03-14 10:07
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CoefficientDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('yscore', models.IntegerField(default=0, help_text='年限得分', verbose_name='年限得分')),
                ('escore', models.IntegerField(default=0, help_text='学历得分', verbose_name='学历得分')),
                ('tscore', models.IntegerField(default=0, help_text='职称得分', verbose_name='职称得分')),
                ('pccbpscore', models.IntegerField(default=0, help_text='银行从业得分', verbose_name='银行从业得分')),
                ('iccbpscore', models.IntegerField(default=0, help_text='中级银行从业得分', verbose_name='中级银行从业得分')),
                ('itscore', models.IntegerField(default=0, help_text='内训师得分', verbose_name='内训师得分')),
                ('cscore', models.IntegerField(default=0, help_text='其他证书得分', verbose_name='其他证书得分')),
                ('totalscore', models.IntegerField(default=0, help_text='总得分', verbose_name='总得分')),
                ('rank', models.IntegerField(default=0, help_text='级次', verbose_name='级次')),
                ('coefficent', models.FloatField(default=0, help_text='系数', verbose_name='系数')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
                ('update_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='修改时间')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '员工系数',
                'verbose_name_plural': '员工系数',
            },
        ),
        migrations.AlterUniqueTogether(
            name='coefficientdetail',
            unique_together=set([('user', 'coefficent')]),
        ),
    ]
