# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-03-12 13:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='clerkrank',
            field=models.IntegerField(choices=[(1, '无'), (2, '见习柜员'), (3, '初级柜员'), (4, '中级柜员'), (5, '高级柜员'), (6, '资深柜员')], default=1, help_text='柜员等级: 1(无),2(见习),3(初级),4(中级),5(高级),6(资深)', verbose_name='柜员等级'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='cmanagerlevel',
            field=models.IntegerField(choices=[(1, '无'), (2, '一等'), (3, '二等'), (4, '三等')], default=1, help_text='客户经理等次: 1(无),2(一等),3(二等),4(三等)', verbose_name='客户经理等次'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='cmanagerrank',
            field=models.IntegerField(choices=[(1, '无'), (2, '初级'), (3, '中级'), (4, '高级')], default=1, help_text='客户经理级次: 1(无),2(初级),3(中级),4(高级)', verbose_name='客户经理级次'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='rank13',
            field=models.IntegerField(default=1, help_text='行员等级(共13等)', verbose_name='行员等级'),
        ),
    ]
