# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-03-12 15:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20180312_1351'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='intermediateccbp',
            field=models.IntegerField(default=0, help_text='中级银行从业', verbose_name='中级银行从业'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='primccbp',
            field=models.IntegerField(default=0, help_text='初级银行从业', verbose_name='初级银行从业'),
        ),
    ]
