# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-03-08 16:22
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('depart', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='indexuserdepart',
            unique_together=set([('user', 'depart')]),
        ),
    ]
